PAIRED_LOGIC_DESCRIPTION_MAP = {}

PAIRED_LOGIC_DESCRIPTION_MAP["percent"] = "DIVIDED BY"
PAIRED_LOGIC_DESCRIPTION_MAP["union"] = "AND"
PAIRED_LOGIC_DESCRIPTION_MAP["difference"] = "SUBTRACTED FROM"

#ISTH_BAT_INSTRUMENT = "ISTH/SSC Bleeding Assessment Tool"

ISTH_BAT_INSTRUMENT = "Bleeding History Questionnaire"

DEMOGRAPHICS_INSTRUMENT = "ISTH/SSC Demographics Tool"

DEFAULT_MULTIPLE_CHOICE_REPORT_QUESTION_IDS = [53,54,55,56,60,61,62,63]

#DEFAULT_MULTIPLE_CHOICE_REPORT_QUESTION_IDS = [21, 22, 23, 24, 28, 29, 30, 31]

#ISTH_SCORE_NAME = "ISTH BAT Score"

ISTH_SCORE_NAME = "V1"

DEFAULT_EMAIL_ID = 'smitra@rockefeller.edu'

EARLIEST_CUTOFF_DATE = '01/01/1981'